import {
  Binary,
  BrainCircuit,
  Cloud,
  Crosshair,
  EyeOff,
  FileCode,
  History,
  KeyRound,
  Lock,
  Monitor,
  Network,
  Radar,
  Repeat,
  Smartphone,
  Sparkles,
  Target,
  Timer,
  Workflow,
  type LucideIcon,
} from "lucide-react";

/** Maps string keys in data files to lucide icon components. */
export const ICONS: Record<string, LucideIcon> = {
  monitor: Monitor,
  smartphone: Smartphone,
  cloud: Cloud,
  network: Network,
  sparkles: Sparkles,
  repeat: Repeat,
  crosshair: Crosshair,
  binary: Binary,
  "key-round": KeyRound,
  timer: Timer,
  "file-code": FileCode,
  history: History,
  target: Target,
  "brain-circuit": BrainCircuit,
  workflow: Workflow,
  lock: Lock,
  "eye-off": EyeOff,
  radar: Radar,
};
